name: RA Tag and Release
description: Tags and publishes pre and stable releases
inputs:
  prerelease:
    description: Indicator of whether or not is a prerelease
    required: false
  files:
    description: String with glob patterns of files that should be uploaded to the release
    required: false

runs:
  using: 'composite'
  steps:
    - name: Tag generation
      id: tag_generation
      uses: paulhatch/semantic-version@v5.0.3
      with:
        tag_prefix: "v"
        major_pattern: (MAJOR)
        minor_pattern: (MINOR)
        version_format: v${major}.${minor}.${patch}
    - name: Tag and Publish release
      id: tag_release
      env:
        tag_name: ${{ steps.tag_generation.outputs.version_tag }}
        target_commitish: ${{ github.sha }}
        prerelease: ${{ inputs.prerelease }}
        files: ${{ inputs.files }}
      uses: actions/github-script@v6
      with:
        retries: 3
        script: |
            const script = require('${{ github.action_path }}/script.js')
    - name: Only publish
      if: ${{ false }}
      uses: softprops/action-gh-release@v0.1.15
      with:
        tag_name: ${steps.tag_release.outputs.tag_name}
        files: ${{ inputs.files }}
        prerelease: ${{inputs.prerelease }}