name: Create tags test
run-name: ${{ github.actor }} is testing creation of release
on:
  workflow_dispatch:
env:
  config-path: holaaaaaaa
  config-patht: hola2
  close-sardoth: hola3
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: firstEnvironment
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Try
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: v1.0.15,
              target_commitish: "0e82f7281d177e87eb5d44acc5429ace3b2716e5"
            })

