name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  pull_request:
env:
  config-path: holaaaaaaa
  config-patht: hola2
  close-sardoth: hola3
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: firstEnvironment
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - run: |
          git branch

          
   
