name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
env:
  config-path: hola
  config-patht: hola2
  close.sardoth: hola3
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    environment: firstEnvironment
    steps:
      - run: echo "ever"
        shell: bash
