name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  workflow_dispatch:
env:
  config-path: hola
  config-patht: hola2
  close-sardoth: hola3
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: firstEnvironment
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Env test
        env:
          suffix: ${{ env.config-path && env.config-patht || env.close-sardoth }}
        run: |
          echo "$suffix"
      - name: Get number of workflows
        uses: actions/github-script@v6
        with:
          retries: 3
          script: |
            const workflowId = await github.rest.actions.getWorkflowRun({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{ github.run_id }}
            });
            
            console.log(workflowId);
        
      - uses: paulhatch/semantic-version@master
        id: semantic
        with:
          version_format: ${major}.${minor}.${patch}-eversardoth
      - run: |
          echo "${{ steps.semantic.outputs.major }}"
          echo "${{ steps.semantic.outputs.minor }}"
          echo "${{ steps.semantic.outputs.patch }}"
          echo "${{ steps.semantic.outputs.increment }}"
          echo "${{ steps.semantic.outputs.version }}"
          echo "${{ steps.semantic.outputs.version_tag }}"
          echo "${{ steps.semantic.outputs.is_tagged }}"
          echo "${{ steps.semantic.outputs.authors }}"
          echo "${{ steps.semantic.outputs.current_commit }}"
          echo "${{ steps.semantic.outputs.previous_commit }}"
          echo "${{ steps.semantic.outputs.previous_version}}"


          
   
