name: Demo workflow to
on: workflow_dispatch
run-name: Demo workflow
jobs:
    demo-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: ./.github/actions/ravere
              with:
                release_type: prerelease

