name: Demo workflow to
on: 
  workflow_dispatch:
    inputs:
      prerelease:
        description: "hola"
        type: boolean
        default: false
run-name: Demo workflow
jobs:
    demo-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - uses: ./.github/actions/ravere
              with:
                prerelease: ${{ inputs.prerelease }}
                files: |
                  README.md
                  pr_number.zip
                  text

